from datetime import datetime
import pandas as pd
import json
import Utils

bugs = {
        "caught": False,
        "critter": 1,
        "bug": "Common Butterfly",
        "location": "Flying",
        "value": 160,
        "time": {4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19},
        "months": "September-June (Northern) / March-December (Southern)",
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": False,
        "aug": False,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 2,
        "bug": "Yellow Butterfly",
        "location": "Flying",
        "value": 160,
        "time": {4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19},
        "months": "September-June (Northern) / March-April, September-December (Southern)",
        "jan": False,
        "feb": False,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": False,
        "aug": False,
        "sep": True,
        "oct": True,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 3,
        "bug": "Tiger Butterfly",
        "location": "Flying",
        "value": 240,
        "time": {4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19},
        "months": "March-September (Northern) / September-March (Southern)",
        "jan": False,
        "feb": False,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 4,
        "bug": "Peacock Butterfly",
        "location": "Flying by hybrid flowers",
        "value": 2500,
        "time": {4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19},
        "months": "March-June (Northern) / September-December (Southern)",
        "jan": False,
        "feb": False,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": False,
        "aug": False,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 5,
        "bug": "Common Bluebottle",
        "location": "Flying",
        "value": 300,
        "time": {4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19},
        "months": "April-August (Northern) / October-February (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 6,
        "bug": "Paper Kite Butterfly",
        "location": "Flying",
        "value": 1000,
        "time": {8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19},
        "months": "Year-round (Northern and Southern)",
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 7,
        "bug": "Great Purple Emperor",
        "location": "Flying",
        "value": "?",
        "time": {4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19},
        "months": "May-August (Northern) / December-March (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 8,
        "bug": "Monach Butterfly",
        "location": "Flying",
        "value": 140,
        "time": {4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17},
        "months": "September-November (Northern) / March-May (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": False,
        "aug": False,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": False
    }, {
        "caught": False,
        "critter": 9,
        "bug": "Emperor Butterfly",
        "location": "Flying",
        "value": 4000,
        "time": {17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8},
        "months": "June-September, December-March (Northern) / December-March, June-September (Southern)",
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": False,
        "may": False,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": True
    }, {
        "caught": True,
        "critter": 10,
        "bug": "Agrias Butterfly",
        "location": "Flying",
        "value": 3000,
        "time": {8, 9, 10, 11, 12, 13, 14, 15, 16, 17},
        "months": "April-September (Northern) / November-March (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 11,
        "bug": "Raja Brooke's Birdwing",
        "location": "Flying",
        "value": 2500,
        "time": {8, 9, 10, 11, 12, 13, 14, 15, 16, 17},
        "months": "April-September, December-February (Northern) / November-March, June-August (Southern)",
        "jan": True,
        "feb": True,
        "mar": False,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": True
    }, {
        "caught": False,
        "critter": 12,
        "bug": "Queen Alexandra's Birdwing",
        "location": "Flying",
        "value": 4000,
        "time": {8, 9, 10, 11, 12, 13, 14, 15, 16},
        "months": "May-September (Northern) / November-March (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 13,
        "bug": "Moth",
        "location": "Flying by light",
        "value": 130,
        "time": {19, 20, 21, 22, 23, 0, 1, 2, 3, 4},
        "months": "Year-round (Northern and Southern)",
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 14,
        "bug": "Atlas Moth",
        "location": "On trees",
        "value": 3000,
        "time": {19, 20, 21, 22, 23, 0, 1, 2, 3, 4},
        "months": "April-September (Northern) / October-March (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 15,
        "bug": "Madagascan Sunset Moth",
        "location": "Flying",
        "value": 2500,
        "time": {8, 9, 10, 11, 12, 13, 14, 15, 16},
        "months": "April-September (Northern) / October-March (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": True,
        "critter": 16,
        "bug": "Long Locust",
        "location": "On ground",
        "value": 200,
        "time": {8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19},
        "months": "April-November (Northern) / November-May (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": False
    }, {
        "caught": False,
        "critter": 17,
        "bug": "Migratory Locust",
        "location": "On ground",
        "value": 600,
        "time": {8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19},
        "months": "August-November (Northern) / February-May (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": False,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": False
    }, {
        "caught": False,
        "critter": 18,
        "bug": "Rice Grasshopper",
        "location": "On ground",
        "value": 160,
        "time": {8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19},
        "months": "August-November (Northern) / February-May (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": False,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": False
    }, {
        "caught": True,
        "critter": 19,
        "bug": "Grasshopper",
        "location": "On ground",
        "value": 160,
        "time": {8, 9, 10, 11, 12, 13, 14, 15, 16, 17},
        "months": "July-September (Northern) / January-March (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": True,
        "critter": 20,
        "bug": "Cricket",
        "location": "On ground",
        "value": 130,
        "time": {17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8},
        "months": "September-November (Northern) / March-May (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": False,
        "aug": False,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": False
    }, {
        "caught": True,
        "critter": 21,
        "bug": "Bell Cricket",
        "location": "On ground",
        "value": 430,
        "time": {17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8},
        "months": "September-October (Northern) / March-April (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": False,
        "aug": False,
        "sep": True,
        "oct": True,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 22,
        "bug": "Mantis",
        "location": "On flowers",
        "value": 430,
        "time": {8, 9, 10, 11, 12, 13, 14, 15, 16, 17},
        "months": "March-November (Northern) / September-May (Southern)",
        "jan": False,
        "feb": False,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": False
    }, {
        "caught": False,
        "critter": 23,
        "bug": "Orchid Mantis",
        "location": "On white flowers",
        "value": 2400,
        "time": {8, 9, 10, 11, 12, 13, 14, 15, 16, 17},
        "months": "March-November (Northern) / September-May (Southern)",
        "jan": False,
        "feb": False,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": False
    }, {
        "caught": False,
        "critter": 24,
        "bug": "Honeybee",
        "location": "Flying near flowers",
        "value": 200,
        "time": {8, 9, 10, 11, 12, 13, 14, 15, 16, 17},
        "months": "March-July (Northern) / March-July (Southern)",
        "jan": False,
        "feb": False,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": False,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 25,
        "bug": "Wasp",
        "location": "Falls from shaking trees",
        "value": 2500,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "months": "Year-round (Northern and Southern)",
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 26,
        "bug": "Brown Cicada",
        "location": "On trees",
        "value": "?",
        "time": {8, 9, 10, 11, 12, 13, 14, 15, 16, 17},
        "months": "July-August (Northern) / January-February (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 27,
        "bug": "Robust Cicada",
        "location": "On trees",
        "value": "?",
        "time": {8, 9, 10, 11, 12, 13, 14, 15, 16, 17},
        "months": "July-August (Northern) / January-February (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 28,
        "bug": "Giant Cicada",
        "location": "On trees",
        "value": "?",
        "time": {8, 9, 10, 11, 12, 13, 14, 15, 16, 17},
        "months": "July-August (Northern) / January-February (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 29,
        "bug": "Walker Cicada",
        "location": "On trees",
        "value": 400,
        "time": {8, 9, 10, 11, 12, 13, 14, 15, 16, 17},
        "months": "August-September (Northern) / February-March (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": False,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 30,
        "bug": "Evening Cicada",
        "location": "On trees",
        "value": "?",
        "time": {4, 5, 6, 7, 8, 16, 17, 18, 19},
        "months": "July-August (Northern) / January-February (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 31,
        "bug": "Cicada Shell",
        "location": "On trees",
        "value": "?",
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "months": "July-August (Northern) / January-February (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": True,
        "critter": 32,
        "bug": "Red Dragonfly",
        "location": "Flying",
        "value": 180,
        "time": {8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19},
        "months": "September-October (Northern) / March-April (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": False,
        "aug": False,
        "sep": True,
        "oct": True,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 33,
        "bug": "Darner Dragonfly",
        "location": "Flying",
        "value": 230,
        "time": {8, 9, 10, 11, 12, 13, 14, 15, 16, 17},
        "months": "April-October (Northern) / October-April (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 34,
        "bug": "Banded Dragonfly",
        "location": "Flying",
        "value": 4500,
        "time": {8, 9, 10, 11, 12, 13, 14, 15, 16, 17},
        "months": "May-October (Northern) / November-April (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 35,
        "bug": "Damselfly",
        "location": "Flying",
        "value": "?",
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "months": "November-February (Northern) / May-August (Southern)",
        "jan": True,
        "feb": True,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": False,
        "aug": False,
        "sep": False,
        "oct": False,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 36,
        "bug": "Firefly",
        "location": "Flying",
        "value": "?",
        "time": {19, 20, 21, 22, 23, 0, 1, 2, 3, 4},
        "months": "June (Northern) / December (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": True,
        "jul": False,
        "aug": False,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 37,
        "bug": "Mole Cricket",
        "location": "Underground",
        "value": 500,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "months": "November-May (Northern) / May-November (Southern)",
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": False,
        "jul": False,
        "aug": False,
        "sep": False,
        "oct": False,
        "nov": True,
        "dec": True
    }, {
        "caught": True,
        "critter": 38,
        "bug": "Pondskater",
        "location": "Ponds",
        "value": 130,
        "time": {8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19},
        "months": "May-September (Northern) / November-March (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": True,
        "critter": 39,
        "bug": "Diving Beetle",
        "location": "Ponds and rivers",
        "value": 800,
        "time": {8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19},
        "months": "May-September (Northern) / November-March (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 40,
        "bug": "Giant Water Bug",
        "location": "Ponds and rivers",
        "value": 2000,
        "time": {19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8},
        "months": "April-September (Northern) / October-March (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 41,
        "bug": "Stinkbug",
        "location": "On flowers",
        "value": 120,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "months": "March-November (Northern) / September-May (Southern)",
        "jan": False,
        "feb": False,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 42,
        "bug": "Man-faced Stink Bug",
        "location": "On flowers",
        "value": 1000,
        "time": {19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8},
        "months": "March-November (Northern) / September-May (Southern)",
        "jan": False,
        "feb": False,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 43,
        "bug": "Ladybug",
        "location": "On flowers",
        "value": 200,
        "time": {8, 9, 10, 11, 12, 13, 14, 15, 16, 17},
        "months": "March-June, October (Northern) / September-December, April (Southern)",
        "jan": False,
        "feb": False,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": False,
        "aug": False,
        "sep": False,
        "oct": True,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 44,
        "bug": "Tiger Beetle",
        "location": "On ground",
        "value": 1500,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "months": "February-November (Northern) / August-May (Southern)",
        "jan": False,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 45,
        "bug": "Jewel Beetle",
        "location": "On trees",
        "value": 2400,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "months": "April-August (Northern) / October-February (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 46,
        "bug": "Violin Beetle",
        "location": "On tree stumps",
        "value": 450,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "months": "May-June, September-November (Northern) / November-December, March-April (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": True,
        "jun": True,
        "jul": False,
        "aug": False,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": False
    }, {
        "caught": False,
        "critter": 47,
        "bug": "Citrus Long-horned Beetle",
        "location": "On tree stumps",
        "value": 350,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "months": "Year-round (Northern and Southern)",
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 48,
        "bug": "Rosalia Batesi Beetle",
        "location": "On tree stumps",
        "value": "?",
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "months": "May-September (Northern) / November-March (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 49,
        "bug": "Blue Weevil Beetle",
        "location": "?",
        "value": "?",
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "months": "July-August (Northern) / January-February (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 50,
        "bug": "Dung Beetle",
        "location": "On ground",
        "value": "?",
        "months": "December-February (Northern) / June-August (Southern)",
        "jan": True,
        "feb": True,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": False,
        "aug": False,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": True
    }, {
        "caught": True,
        "critter": 51,
        "bug": "Earth-boring Dung Beetle",
        "location": "On ground",
        "value": 300,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "months": "July-September (Northern) / January-March (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 52,
        "bug": "Scarab Beetle",
        "location": "On trees",
        "value": "?",
        "time": {23, 0, 1, 2, 3, 4, 5, 6, 7, 8},
        "months": "July-August (Northern) / January-February (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 53,
        "bug": "Drone Beetle",
        "location": "On trees",
        "value": "?",
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "months": "June-August (Northern) / December-February (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 54,
        "bug": "Goliath Beetle",
        "location": "On trees",
        "value": "?",
        "time": {17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8},
        "months": "June-September (Northern) / December-March (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 55,
        "bug": "Saw Stag",
        "location": "On trees",
        "value": "?",
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "months": "July-August (Northern) / January-February (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 56,
        "bug": "Miyama Stag",
        "location": "On trees",
        "value": "?",
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "months": "July-August (Northern) / January-February (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 57,
        "bug": "Giant Stag",
        "location": "On trees",
        "value": "?",
        "time": {23, 0, 1, 2, 3, 4, 5, 6, 7, 8},
        "months": "July-August (Northern) / January-February (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 58,
        "bug": "Rainbow Stag",
        "location": "On trees",
        "value": "?",
        "time": {19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8},
        "months": "June-September (Northern) / December-March (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 59,
        "bug": "Cyclommatus Stag",
        "location": "On trees",
        "value": "?",
        "time": {17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8},
        "months": "July-August (Northern) / January-February (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 60,
        "bug": "Golden Stag",
        "location": "On trees",
        "value": "?",
        "time": {17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8},
        "months": "July-August (Northern) / January-February (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 61,
        "bug": "Giraffe Stag",
        "location": "On trees",
        "value": "?",
        "time": {17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8},
        "months": "July-August (Northern) / January-February (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 62,
        "bug": "Horned Dynastid",
        "location": "On trees",
        "value": "?",
        "time": {17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8},
        "months": "July-August (Northern) / January-February (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 63,
        "bug": "Horned Atlas",
        "location": "On trees",
        "value": "?",
        "time": {17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8},
        "months": "July-August (Northern) / January-February (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 64,
        "bug": "Horned Elephant",
        "location": "On trees",
        "value": "?",
        "time": {17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8},
        "months": "July-August (Northern) / January-February (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 65,
        "bug": "Horned Herucles",
        "location": "On trees",
        "value": "?",
        "time": {17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8},
        "months": "July-August (Northern) / January-February (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 66,
        "bug": "Walking Stick",
        "location": "Falls from shaking trees",
        "value": "?",
        "time": {4, 5, 6, 7, 8, 17, 18, 19},
        "months": "July-November (Northern) / January-May (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": False
    }, {
        "caught": False,
        "critter": 67,
        "bug": "Walking Leaf",
        "location": "Near trees, disguised as furniture leaf",
        "value": 600,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "months": "July-August (Northern) / January-March (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 68,
        "bug": "Bagworm",
        "location": "Falls from shaking trees",
        "value": 600,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "months": "Year-round (Northern and Southern)",
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 69,
        "bug": "Ant",
        "location": "On rotten food",
        "value": "?",
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "months": "Year-round (Northern and Southern)",
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 70,
        "bug": "Hermit Crab",
        "location": "Beach",
        "value": 1000,
        "time": {19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8},
        "months": "Year-round (Northern and Southern)",
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 71,
        "bug": "Wharf Roach",
        "location": "On rocks at beach",
        "value": 200,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "months": "Year-round (Northern and Southern)",
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 72,
        "bug": "Fly",
        "location": "On trash items",
        "value": "?",
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "months": "Year-round (Northern and Southern)",
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 73,
        "bug": "Mosquito",
        "location": "Flying",
        "value": 130,
        "time": {17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4},
        "months": "June-September (Northern) / December-March (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 74,
        "bug": "Flea",
        "location": "On villagers",
        "value": "?",
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "months": "April-November (Northern) / October-May (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": False
    }, {
        "caught": False,
        "critter": 75,
        "bug": "Snail",
        "location": "On rocks (raining)",
        "value": 250,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "months": "Year-round (Northern and Southern)",
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 76,
        "bug": "Pill Bug",
        "location": "Hit rocks",
        "value": 250,
        "time": {23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16},
        "months": "September-June (Northern) / March-December (Southern)",
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": False,
        "aug": False,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 77,
        "bug": "Centipede",
        "location": "Hit rocks",
        "value": 300,
        "time": {16, 17, 18, 19, 20, 21, 22, 23},
        "months": "September-June (Northern) / March-December (Southern)",
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": False,
        "aug": False,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 78,
        "bug": "Spider",
        "location": "Falls from shaking trees",
        "value": 480,
        "time": {19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8},
        "months": "Year-round (Northern and Southern)",
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 79,
        "bug": "Tarantula",
        "location": "On ground",
        "value": 8000,
        "time": {19, 20, 21, 22, 23, 0, 1, 2, 3, 4},
        "months": "November-April (Northern) / May-October (Southern)",
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": False,
        "jun": False,
        "jul": False,
        "aug": False,
        "sep": False,
        "oct": False,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 80,
        "bug": "Scorpion",
        "location": "On ground",
        "value": 8000,
        "time": {19, 20, 21, 22, 23, 0, 1, 2, 3, 4},
        "months": "May-October (Northern) / November-April (Southern)",
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": False,
        "dec": False
    }


df = Utils.bugs_dataframe(bugs)
print(df.keys())

"""TODO: new_bugs() - check which bugs are available this month that weren't last month"""
"""TODO: expiring_bugs() (name pending), check bugs available this month that won't be available next month"""
"""TODO: get_info(bug) - return information on when & where bug will be available"""