from datetime import datetime
import pandas as pd
import numpy
months = ["m", "jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"]
current_month = months[datetime.now().month]
current_hour = datetime.now().hour

fishes = {
        "caught": False,
        "critter": 1,
        "fish": "Bitterling",
        "location": "River",
        "shadowSize": "Smallest",
        "value": 900,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "feb": True,
        "mar": True,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": False,
        "aug": False,
        "sep": False,
        "oct": False,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 21,
        "fish": "Yellow Perch",
        "location": "River",
        "shadowSize": "Medium",
        "value": 300,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "feb": True,
        "mar": True,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": False,
        "aug": False,
        "sep": False,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 30,
        "fish": "Stringfish",
        "location": "River (Clifftop)",
        "shadowSize": "Largest",
        "value": 15000,
        "time": {16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
        "feb": True,
        "mar": True,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": False,
        "aug": False,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": True
    }, {
        "caught": False,
        "critter": 46,
        "fish": "Sturgeon",
        "location": "River (mouth)",
        "shadowSize": "Largest",
        "value": 10000,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "feb": True,
        "mar": True,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": False,
        "aug": False,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 47,
        "fish": "Sea Butterfly",
        "location": "Sea",
        "shadowSize": "Smallest",
        "value": 1000,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "feb": True,
        "mar": True,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": False,
        "aug": False,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": True
    }, {
        "caught": False,
        "critter": 77,
        "fish": "Football Fish",
        "location": "Sea",
        "shadowSize": "Large",
        "value": 2500,
        "time": {16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
        "feb": True,
        "mar": True,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": False,
        "aug": False,
        "sep": False,
        "oct": False,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 2,
        "fish": "Pale Chub",
        "location": "River",
        "shadowSize": "Smallest",
        "value": 160,
        "time": {9, 10, 11, 12, 13, 14, 15, 16},
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 3,
        "fish": "Crucian Carp",
        "location": "River",
        "shadowSize": "Small",
        "value": 160,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 4,
        "fish": "Dace",
        "location": "River",
        "shadowSize": "Medium",
        "value": 240,
        "time": {16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 5,
        "fish": "Carp",
        "location": "Pond",
        "shadowSize": "Large",
        "value": 300,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 6,
        "fish": "Koi",
        "location": "Pond",
        "shadowSize": "Large",
        "value": 4000,
        "time": {16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 7,
        "fish": "Goldfish",
        "location": "Pond",
        "shadowSize": "Smallest",
        "value": 1300,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 8,
        "fish": "Pop-eyed Goldfish",
        "location": "Pond",
        "shadowSize": "Smallest",
        "value": 1300,
        "time": {9, 10, 11, 12, 13, 14, 15, 16},
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 9,
        "fish": "Ranchu Goldfish",
        "location": "Pond",
        "shadowSize": "Small",
        "value": 4500,
        "time": {9, 10, 11, 12, 13, 14, 15, 16},
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 10,
        "fish": "Killifish",
        "location": "Pond",
        "shadowSize": "Smallest",
        "value": "?",
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "feb": False,
        "mar": False,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 11,
        "fish": "Crawfish",
        "location": "Pond",
        "shadowSize": "Medium",
        "value": 200,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "feb": False,
        "mar": False,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 12,
        "fish": "Soft-shelled Turtle",
        "location": "River",
        "shadowSize": "?",
        "value": 3750,
        "time": {16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": False,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 13,
        "fish": "Snapping Turtle",
        "location": "River",
        "shadowSize": "?",
        "value": 5000,
        "time": {9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4},
        "feb": False,
        "mar": False,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 14,
        "fish": "Tadpole",
        "location": "Pond",
        "shadowSize": "Smallest",
        "value": 100,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "feb": False,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": False,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 15,
        "fish": "Frog",
        "location": "Pond",
        "shadowSize": "Small",
        "value": "?",
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "feb": False,
        "mar": False,
        "apr": False,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 16,
        "fish": "Freshwater Goby",
        "location": "River",
        "shadowSize": "Small",
        "value": 400,
        "time": {16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 17,
        "fish": "Loach",
        "location": "River",
        "shadowSize": "Small",
        "value": 400,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "feb": False,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": False,
        "jul": False,
        "aug": False,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 18,
        "fish": "Catfish",
        "location": "Pond",
        "shadowSize": "?",
        "value": 800,
        "time": {16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
        "feb": False,
        "mar": False,
        "apr": False,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 19,
        "fish": "Giant Snakehead",
        "location": "Pond",
        "shadowSize": "X Large",
        "value": "?",
        "time": {9, 10, 11, 12, 13, 14, 15, 16},
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 20,
        "fish": "Bluegill",
        "location": "River",
        "shadowSize": "Small",
        "value": 180,
        "time": {9, 10, 11, 12, 13, 14, 15, 16},
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 22,
        "fish": "Black Bass",
        "location": "River",
        "shadowSize": "Large",
        "value": 400,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 23,
        "fish": "Tilapia",
        "location": "River",
        "shadowSize": "?",
        "value": 800,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 24,
        "fish": "Pike",
        "location": "River",
        "shadowSize": "X Large",
        "value": 1800,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": False,
        "aug": False,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 25,
        "fish": "Pond Smelt",
        "location": "River",
        "shadowSize": "Small",
        "value": "?",
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "feb": True,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": False,
        "aug": False,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": True
    }, {
        "caught": False,
        "critter": 26,
        "fish": "Sweetfish",
        "location": "River",
        "shadowSize": "Medium",
        "value": 900,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 27,
        "fish": "Cherry Salmon",
        "location": "River (Clifftop)",
        "shadowSize": "Medium",
        "value": 1000,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "feb": False,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": False,
        "aug": False,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": False
    }, {
        "caught": False,
        "critter": 28,
        "fish": "Char",
        "location": "River (Clifftop)",
        "shadowSize": "Medium",
        "value": 3800,
        "time": {16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
        "jan": False,
        "feb": False,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": False,
        "aug": False,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": False
    }, {
        "caught": False,
        "critter": 29,
        "fish": "Golden Trout",
        "location": "River (Clifftop)",
        "shadowSize": "Large",
        "value": 15000,
        "time": {16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
        "jan": False,
        "feb": False,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": False,
        "jul": False,
        "aug": False,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": False
    }, {
        "caught": False,
        "critter": 31,
        "fish": "Salmon",
        "location": "River (mouth)",
        "shadowSize": "Small",
        "value": 700,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": False,
        "aug": False,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 32,
        "fish": "King Salmon",
        "location": "River (mouth)",
        "shadowSize": "Smallest",
        "value": 1800,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": False,
        "aug": False,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 33,
        "fish": "Mitten Crab",
        "location": "River",
        "shadowSize": "Small",
        "value": 2000,
        "time": {16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": False,
        "aug": False,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": False
    }, {
        "caught": False,
        "critter": 34,
        "fish": "Guppy",
        "location": "River",
        "shadowSize": "Smallest",
        "value": "?",
        "time": {9, 10, 11, 12, 13, 14, 15, 16},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": False
    }, {
        "caught": False,
        "critter": 35,
        "fish": "Nibble Fish",
        "location": "River",
        "shadowSize": "Small",
        "value": 1500,
        "time": {9, 10, 11, 12, 13, 14, 15, 16},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 36,
        "fish": "Angelfish",
        "location": "River",
        "shadowSize": "Small",
        "value": 3000,
        "time": {16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 37,
        "fish": "Betta",
        "location": "River",
        "shadowSize": "Small",
        "value": 2500,
        "time": {9, 10, 11, 12, 13, 14, 15, 16},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 38,
        "fish": "Neon Tetra",
        "location": "River",
        "shadowSize": "Smallest",
        "value": 500,
        "time": {9, 10, 11, 12, 13, 14, 15, 16},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": False
    }, {
        "caught": False,
        "critter": 39,
        "fish": "Rainbowfish",
        "location": "River",
        "shadowSize": "Small",
        "value": 800,
        "time": {9, 10, 11, 12, 13, 14, 15, 16},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 40,
        "fish": "Piranha",
        "location": "River",
        "shadowSize": "Small",
        "value": 2500,
        "time": {0, 1, 2, 3, 4, 9, 10, 11, 12, 13, 14, 15, 16, 21, 22, 23},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 41,
        "fish": "Arowana",
        "location": "River",
        "shadowSize": "Large",
        "value": 10000,
        "time": {16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 42,
        "fish": "Dorado",
        "location": "River",
        "shadowSize": "X Large",
        "value": 15000,
        "time": {4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21},
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 43,
        "fish": "Gar",
        "location": "Pond",
        "shadowSize": "Largest",
        "value": 6000,
        "time": {16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 44,
        "fish": "Arapaima",
        "location": "River",
        "shadowSize": "?",
        "value": 10000,
        "time": {16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 45,
        "fish": "Saddled Bichir",
        "location": "River",
        "shadowSize": "Large",
        "value": 4000,
        "time": {21, 22, 23, 0, 1, 2, 3, 4},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 48,
        "fish": "Sea Horse",
        "location": "Sea",
        "shadowSize": "Smallest",
        "value": 1100,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": False
    }, {
        "caught": False,
        "critter": 49,
        "fish": "Clown Fish",
        "location": "Sea",
        "shadowSize": "Smallest",
        "value": 650,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 50,
        "fish": "Surgeonfish",
        "location": "Sea",
        "shadowSize": "Small",
        "value": 1000,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 51,
        "fish": "Butterfly Fish",
        "location": "Sea",
        "shadowSize": "Small",
        "value": 1000,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 52,
        "fish": "Napoleonfish",
        "location": "Sea",
        "shadowSize": "Largest",
        "value": 10000,
        "time": {4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 53,
        "fish": "Zebra Turkeyfish",
        "location": "Sea",
        "shadowSize": "Medium",
        "value": 500,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": True,
        "may": True,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": False
    }, {
        "caught": False,
        "critter": 54,
        "fish": "Blowfish",
        "location": "Sea",
        "shadowSize": "Medium",
        "value": "?",
        "time": {18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4},
        "jan": True,
        "feb": True,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": False,
        "aug": False,
        "sep": False,
        "oct": False,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 55,
        "fish": "Puffer Fish",
        "location": "Sea",
        "shadowSize": "Medium",
        "value": 250,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 56,
        "fish": "Anchovy",
        "location": "Sea",
        "shadowSize": "Small",
        "value": 200,
        "time": {4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21},
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 57,
        "fish": "Horse Mackerel",
        "location": "Sea",
        "shadowSize": "Small",
        "value": 150,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 58,
        "fish": "Barred Knifejaw",
        "location": "Sea",
        "shadowSize": "Medium",
        "value": 5000,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "jan": False,
        "feb": False,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": False
    }, {
        "caught": False,
        "critter": 59,
        "fish": "Sea Bass",
        "location": "Sea",
        "shadowSize": "X Large",
        "value": 400,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 60,
        "fish": "Red Snapper",
        "location": "Sea",
        "shadowSize": "Medium",
        "value": 3000,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 61,
        "fish": "Dab",
        "location": "Sea",
        "shadowSize": "Medium",
        "value": 300,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": False,
        "jun": False,
        "jul": False,
        "aug": False,
        "sep": False,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 62,
        "fish": "Olive Flounder",
        "location": "Sea",
        "shadowSize": "Large",
        "value": 800,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 63,
        "fish": "Squid",
        "location": "Sea",
        "shadowSize": "Medium",
        "value": 500,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": True
    }, {
        "caught": False,
        "critter": 64,
        "fish": "Moray Eel",
        "location": "Sea",
        "shadowSize": "X Large",
        "value": 2000,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": False,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 65,
        "fish": "Ribbon Eel",
        "location": "Sea",
        "shadowSize": "Narrow",
        "value": 600,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 66,
        "fish": "Tuna",
        "location": "Pier",
        "shadowSize": "X Large",
        "value": 7000,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": False,
        "jun": False,
        "jul": False,
        "aug": False,
        "sep": False,
        "oct": False,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 67,
        "fish": "Blue Marlin",
        "location": "Pier",
        "shadowSize": "X Large",
        "value": 10000,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": False,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 68,
        "fish": "Giant Trevally",
        "location": "Pier",
        "shadowSize": "Large",
        "value": "?",
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 69,
        "fish": "Mahi-mahi",
        "location": "Sea",
        "shadowSize": "Large",
        "value": 6000,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 70,
        "fish": "Ocean Sunfish",
        "location": "Sea",
        "shadowSize": "(Fin)",
        "value": 4000,
        "time": {4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 71,
        "fish": "Ray",
        "location": "Sea",
        "shadowSize": "X Large",
        "value": 3000,
        "time": {4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": False,
        "jul": False,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": False
    }, {
        "caught": False,
        "critter": 72,
        "fish": "Saw Shark",
        "location": "Sea",
        "shadowSize": "Largest (fin)",
        "value": 12000,
        "time": {16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 73,
        "fish": "Hammerhead Shark",
        "location": "Sea",
        "shadowSize": "Largest (fin)",
        "value": 8000,
        "time": {16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 74,
        "fish": "Great White Shark",
        "location": "Sea",
        "shadowSize": "Largest (fin)",
        "value": 15000,
        "time": {16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 75,
        "fish": "Whale Shark",
        "location": "Sea",
        "shadowSize": "Largest (fin)",
        "value": 13000,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 76,
        "fish": "Suckerfish",
        "location": "Sea",
        "shadowSize": "(Fin)",
        "value": 1500,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "jan": False,
        "feb": False,
        "mar": False,
        "apr": False,
        "may": False,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": False,
        "nov": False,
        "dec": False
    }, {
        "caught": False,
        "critter": 78,
        "fish": "Oarfish",
        "location": "Sea",
        "shadowSize": "Largest",
        "value": 9000,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": False,
        "jul": False,
        "aug": False,
        "sep": False,
        "oct": False,
        "nov": False,
        "dec": True
    }, {
        "caught": False,
        "critter": 79,
        "fish": "Barreleye",
        "location": "Sea",
        "shadowSize": "Small",
        "value": 15000,
        "time": {21, 22, 23, 0, 1, 2, 3, 4},
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
    }, {
        "caught": False,
        "critter": 80,
        "fish": "Coelacanth",
        "location": "Sea (rainy days)",
        "shadowSize": "Largest",
        "value": 15000,
        "time": {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        "jan": True,
        "feb": True,
        "mar": True,
        "apr": True,
        "may": True,
        "jun": True,
        "jul": True,
        "aug": True,
        "sep": True,
        "oct": True,
        "nov": True,
        "dec": True
}

def __format_size(size):
    sizes = {
        "largeish": ["large", "x large", "largest"],
        "smallish": ["smallest", "small"],
        "any": ["smallest", "small", "medium", "large", "x large", "largest"]
    }
    if size in sizes:
        return sizes[size]
    return size.lower()

def __format_loc(loc):
    locations = {
        "river": "River",
        "rivercliff": "River (Clifftop)",
        "rivermouth": "River (mouth)",
        "sea": ["Sea", "Pier"],
        "pond": "Pond",
        "any": ["River", "River (Clifftop)", "River (mouth)", "Sea", "Sea (rainy days)", "Pier", "Pond"]}
    return locations[loc]

def __crosstable_to_tidy(table=None, attribute_field_name=None, data_field_name=None, sheet='all', qualifying_fields=1):
    
    ''' Reads a file or dataframe that contains data of crosstable structure, i.e. orthogonal, 
        and returns a tidy dataframe, more suitable for further analysis.
        
        {table: path/url string to excel file or pandas.core.frame.DataFrame object,
        attribute_field_name: name of column that will be stacked,
        data_field_name: name of column that will contain data values,
        sheet: load specific sheet or ('all') loop through and concatenate crosstables from all excel-file sheets,
        qualifying_fields: number of table columns that should be left as-is}'''
    
    if isinstance(table, str):
        if sheet == 'all':
            df_crosstab_dict = pd.read_excel(table, sheet_name=None, index_col=list(range(qualifying_fields)))
            df_crosstab_tmp = [v for v in df_crosstab_dict.values()]
            df_crosstab = pd.concat(df_crosstab_tmp)
        else:
            df_crosstab = pd.read_excel(table, sheet_name=sheet, index_col=list(range(qualifying_fields)))
    elif isinstance(table, pd.core.frame.DataFrame):
        df_crosstab = table        
    else:
        return 'No data was passed to function'
    
    if not isinstance(df_crosstab.index, pd.MultiIndex):
        df_crosstab = df_crosstab.set_index(list(df_crosstab.columns[:qualifying_fields]))
        
    df_crosstab = df_crosstab.stack().reset_index()
        
    col_names = [attribute_field_name, data_field_name]
    col_names_map = dict(zip(df_crosstab.columns[qualifying_fields:], col_names))
    df_crosstab.rename(columns=col_names_map, inplace=True)
    
    return df_crosstab

def __fish_dataframe(fishes_input):
    fish_dict = {i: d for i, d in enumerate(fishes_input)}
    times = {}
    for k in fish_dict.keys():
        diff = set(range(25)) - fish_dict[k]['time'] #missing hours
        diffs = ['NA']*len(diff) #'NA' inplace of missing hours
        times[k] = list(fish_dict[k]['time']) + diffs #add missing hours to original times

    df = pd.DataFrame(fish_dict).transpose()
    df_time = pd.DataFrame(times).transpose()

    df_base = df[['fish', 'location', 'shadowSize', 'value']]
    df_months = df[['fish', 'location', 'shadowSize', 'value',  'jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec']]
    df_times = pd.merge(df_base, df_time, how='outer', on=df.index)

    df_months_tidy = __crosstable_to_tidy(df_months, 'Months', 'isMonth', qualifying_fields=4)
    df_times_tidy = __crosstable_to_tidy(df_times.drop('key_0', axis=1), 'Times', 'isTime', qualifying_fields=4)
    df_times_tidy['isTime'] = df_times_tidy['isTime'].apply(lambda x: True if x != 'NA' else False)

    df_final = pd.merge(df_months_tidy, df_times_tidy, how='outer', on=['fish', 'location', 'shadowSize', 'value'])

    return df_final

def get_fish(size, loc):
    """filter first by loc, then size, then time"""
    size = __format_size(size) 
    loc = __format_loc(loc)

    possible_fish = []
    for fish in fishes:
        if fish["location"] in loc or ("Sea" in fish["location"] and "Sea" in loc):
            if fish["shadowSize"].casefold() in size:
                if fish[current_month] and current_hour in fish["time"]:
                    f = fish["fish"]
                    if "pier" in fish["location"].casefold():
                        f += " (pier)"
                    elif "rain" in fish["location"].casefold():
                        f += " (rainy days)"
                    possible_fish.append(f)
    return possible_fish

df = __fish_dataframe(fishes)

# locs = ['River']
# filter_month = (df['Months'] == current_month) & df['isMonth']
# filter_hour = (df['Times'] == current_hour) & df['isTime']
# filter_loc = df['location'] in locs
# result = df[filter_month & filter_hour]['fish'].values
# print(result)
